[package]
name = "mipsy_instructions"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.26"
mipsy_lib = { path = "../mipsy_lib" }

[features]
rt_yaml = []
